echo enabling no porvisioning...
adb shell settings put global net.tethering.noprovisioning true
echo disabling thethering entitlement check...
adb shell settings put global tether_entitlement_check_state 0
echo disabling tether dun requirement...
adb shell settings put global tether_dun_required 0
echo Changing TTL...
sudo iptables -t mangle -A POSTROUTING -j TTL --ttl-set 65
